//! Deterministic Page Object generation from [`ElementMap`].

use crate::element_map::{ClusterType, ElementMap, ElementNode};
use crate::CoreError;
use serde::{Deserialize, Serialize};
use std::fmt::Write;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateOptions {
    #[serde(default = "default_language")]
    pub language: String,
    #[serde(default = "default_class_name")]
    pub class_name: String,
    #[serde(default)]
    pub package_name: Option<String>,
    #[serde(default = "default_true")]
    pub include_signatures: bool,
}

fn default_language() -> String {
    "java_playwright".to_string()
}

fn default_class_name() -> String {
    "GeneratedPage".to_string()
}

fn default_true() -> bool {
    true
}

impl Default for GenerateOptions {
    fn default() -> Self {
        Self {
            language: default_language(),
            class_name: default_class_name(),
            package_name: None,
            include_signatures: default_true(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedArtifact {
    pub files: Vec<GeneratedFile>,
}

pub fn generate_page_object(map: &ElementMap, options: &GenerateOptions) -> GeneratedArtifact {
    let content = match options.language.as_str() {
        "java_playwright" => generate_java_playwright(map, options),
        other => format!("// Unsupported language: {other}\n"),
    };

    let path = options
        .package_name
        .as_ref()
        .map(|pkg| format!("{}/{}.java", pkg.replace('.', "/"), options.class_name))
        .unwrap_or_else(|| format!("{}.java", options.class_name));

    GeneratedArtifact {
        files: vec![GeneratedFile { path, content }],
    }
}

pub fn generate_page_object_json(map_json: &str, options_json: &str) -> Result<String, CoreError> {
    let map: ElementMap = serde_json::from_str(map_json)?;
    let options: GenerateOptions = if options_json.trim().is_empty() {
        GenerateOptions::default()
    } else {
        serde_json::from_str(options_json)?
    };
    let artifact = generate_page_object(&map, &options);
    Ok(serde_json::to_string(&artifact)?)
}

fn generate_java_playwright(map: &ElementMap, options: &GenerateOptions) -> String {
    let mut out = String::new();

    if let Some(pkg) = &options.package_name {
        writeln!(out, "package {pkg};\n").unwrap();
    }

    writeln!(
        out,
        "import com.microsoft.playwright.Locator;\nimport com.microsoft.playwright.Page;\n"
    )
    .unwrap();

    writeln!(out, "/** Generated by Frap — do not edit by hand. */").unwrap();
    writeln!(out, "public class {} {{", options.class_name).unwrap();
    writeln!(out, "    private final Page page;\n").unwrap();
    writeln!(out, "    public {}(Page page) {{", options.class_name).unwrap();
    writeln!(out, "        this.page = page;").unwrap();
    writeln!(out, "    }}").unwrap();

    let mut emitted_clusters = std::collections::HashSet::new();
    let mut used_names: std::collections::HashSet<String> = std::collections::HashSet::new();

    for cluster in &map.clusters {
        if cluster.cluster_type != ClusterType::List || cluster.element_ids.len() < 2 {
            continue;
        }
        if !emitted_clusters.insert(cluster.id.clone()) {
            continue;
        }
        let method = unique_name(cluster_method_name(&cluster.prefix_signature), &mut used_names);
        let sample = cluster
            .element_ids
            .first()
            .and_then(|id| map.elements.iter().find(|e| &e.id == id));
        if let Some(el) = sample {
            writeln!(
                out,
                "\n    /** Cluster `{}` ({} elements) */",
                cluster.id,
                cluster.element_ids.len()
            )
            .unwrap();
            writeln!(out, "    public Locator {}(int index) {{", method).unwrap();
            writeln!(
                out,
                "        return page.locator(\"{}\").nth(index);",
                escape_java_string(&el.recommended_selector)
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
    }

    for element in &map.elements {
        let method = unique_name(element_method_name(element), &mut used_names);
        writeln!(
            out,
            "\n    /** {} (confidence {:.2}) */",
            element.tag, element.confidence
        )
        .unwrap();
        if options.include_signatures {
            writeln!(out, "    // signature prefix: {}", element.signature.prefix).unwrap();
        }
        writeln!(out, "    public Locator {}() {{", method).unwrap();
        writeln!(
            out,
            "        return page.locator(\"{}\");",
            escape_java_string(&element.recommended_selector)
        )
        .unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}\n").unwrap();
    out
}

fn element_method_name(element: &ElementNode) -> String {
    let name = to_camel_case(&transliterate(&method_name_source(element)));
    if name.is_empty() {
        to_camel_case(&format!("{}_element", element.tag))
    } else {
        name
    }
}

/// Picks the human source for a method name from the element semantics, in
/// priority order: `data-testid` → `aria-label` → semantic `id` → `name` →
/// visible text → synthetic fallback.
fn method_name_source(element: &ElementNode) -> String {
    let attrs = &element.signature.stable_attrs;
    for key in ["data-testid", "aria-label", "name"] {
        if let Some(v) = attrs.get(key) {
            if !v.trim().is_empty() {
                return v.clone();
            }
        }
    }
    if let Some(id) = attrs.get("id") {
        if id_is_namelike(id) {
            return id.clone();
        }
    }
    if let Some(text) = &element.signature.text_content {
        let text = text.split_whitespace().collect::<Vec<_>>().join(" ");
        if !text.is_empty() && text.chars().count() <= 40 {
            return text;
        }
    }
    format!("{}_{}", element.tag, element.id)
}

/// An id is good as a method name if it reads like a label: it has letters and
/// is not number-dominant or uuid-like. (Stricter `looks_like_generated` is for
/// rejecting *selectors*, and over-rejects semantic ids like `nav-link-pay`.)
fn id_is_namelike(id: &str) -> bool {
    let id = id.trim();
    let letters = id.chars().filter(|c| c.is_alphabetic()).count();
    let digits = id.chars().filter(|c| c.is_ascii_digit()).count();
    letters >= 2 && digits * 2 < id.chars().count() && !id.contains("uuid")
}

/// Transliterates Cyrillic to Latin so names stay valid Java identifiers.
/// Non-Cyrillic characters are kept as-is (word boundaries handled downstream).
fn transliterate(input: &str) -> String {
    let mut out = String::new();
    for ch in input.chars() {
        let lower = ch.to_lowercase().next().unwrap_or(ch);
        let mapped = match lower {
            'а' => "a", 'б' => "b", 'в' => "v", 'г' => "g", 'д' => "d",
            'е' | 'ё' | 'э' => "e", 'ж' => "zh", 'з' => "z", 'и' => "i",
            'й' => "y", 'к' => "k", 'л' => "l", 'м' => "m", 'н' => "n",
            'о' => "o", 'п' => "p", 'р' => "r", 'с' => "s", 'т' => "t",
            'у' => "u", 'ф' => "f", 'х' => "h", 'ц' => "ts", 'ч' => "ch",
            'ш' => "sh", 'щ' => "sch", 'ы' => "y", 'ю' => "yu", 'я' => "ya",
            'ъ' | 'ь' => "",
            _ => {
                out.push(ch);
                continue;
            }
        };
        out.push_str(mapped);
    }
    out
}

/// Ensures a method name is unique within the class by adding a numeric suffix.
fn unique_name(base: String, used: &mut std::collections::HashSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }
    let mut n = 2;
    loop {
        let candidate = format!("{base}{n}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        n += 1;
    }
}

fn cluster_method_name(prefix: &str) -> String {
    let sanitized: String = prefix
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect();
    to_camel_case(&format!("cluster_{sanitized}"))
}

fn to_camel_case(input: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in input.chars() {
        if !c.is_alphanumeric() {
            upper_next = true;
            continue;
        }
        if out.is_empty() {
            out.push(c.to_ascii_lowercase());
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        "element".to_string()
    } else {
        out
    }
}

fn escape_java_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::element_map::{build_element_map, MapOptions};
    use crate::DOMSnapshot;

    #[test]
    fn generates_java_with_class_and_locators() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![crate::DOMElementInfo {
                selector: "[data-testid='submit']".to_string(),
                tag: "button".to_string(),
                attributes: [("data-testid".to_string(), "submit".to_string())].into(),
                text_content: Some("OK".to_string()),
                path: vec!["button:-".to_string()],
                position_in_parent: None,
            }],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let artifact = generate_page_object(
            &map,
            &GenerateOptions {
                class_name: "CheckoutPage".to_string(),
                package_name: Some("com.example.pages".to_string()),
                ..Default::default()
            },
        );
        let source = &artifact.files[0].content;
        assert!(source.contains("public class CheckoutPage"));
        assert!(source.contains("package com.example.pages"));
        assert!(source.contains("page.locator"));
    }

    fn one(selector: &str, tag: &str, attrs: &[(&str, &str)], text: Option<&str>) -> String {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![crate::DOMElementInfo {
                selector: selector.to_string(),
                tag: tag.to_string(),
                attributes: attrs
                    .iter()
                    .map(|(k, v)| (k.to_string(), v.to_string()))
                    .collect(),
                text_content: text.map(|t| t.to_string()),
                path: vec![format!("{tag}:-")],
                position_in_parent: None,
            }],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        generate_page_object(&map, &GenerateOptions::default()).files[0]
            .content
            .clone()
    }

    #[test]
    fn transliterate_cyrillic_to_latin() {
        assert_eq!(transliterate("Между своими"), "mezhdu svoimi");
        assert_eq!(transliterate("Оплатить"), "oplatit");
        assert_eq!(transliterate("nav-link"), "nav-link");
    }

    // issue #05: names come from semantics, not tag+strategy+el-N.
    #[test]
    fn method_name_from_testid() {
        assert!(one("x", "button", &[("data-testid", "remove-btn")], None).contains("Locator removeBtn()"));
    }

    #[test]
    fn method_name_from_id_when_no_testid() {
        assert!(one("x", "a", &[("id", "nav-link-payments")], None).contains("Locator navLinkPayments()"));
    }

    #[test]
    fn method_name_from_aria_label() {
        assert!(one("x", "button", &[("aria-label", "Log out")], None).contains("Locator logOut()"));
    }

    #[test]
    fn method_name_from_cyrillic_text() {
        let src = one("x", "a", &[], Some("Между своими"));
        assert!(src.contains("Locator mezhduSvoimi()"), "{src}");
    }

    #[test]
    fn method_name_has_no_strategy_or_synthetic_id() {
        let src = one("x", "button", &[("data-testid", "remove-btn")], None);
        assert!(!src.contains("buttondatatestid"));
        assert!(!src.contains("El0"));
    }

    // issue #05: names must stay unique after disambiguation.
    // The two elements collide on the NAME source ("pay") but have DIFFERENT
    // selectors, so selector-dedup does not fold them and naming is exercised.
    #[test]
    fn colliding_names_get_numeric_suffix() {
        let snapshot = DOMSnapshot {
            html: String::new(),
            elements: vec![
                crate::DOMElementInfo {
                    selector: "x".into(),
                    tag: "button".into(),
                    attributes: [("data-testid".to_string(), "pay".to_string())].into(),
                    text_content: None,
                    path: vec!["div:-".into(), "button:-".into()],
                    position_in_parent: Some(0),
                },
                crate::DOMElementInfo {
                    selector: "y".into(),
                    tag: "button".into(),
                    attributes: [("aria-label".to_string(), "Pay".to_string())].into(),
                    text_content: None,
                    path: vec!["section:-".into(), "button:-".into()],
                    position_in_parent: Some(0),
                },
            ],
        };
        let map = build_element_map(&snapshot, &MapOptions::default());
        let src = generate_page_object(&map, &GenerateOptions::default()).files[0]
            .content
            .clone();
        assert!(src.contains("Locator pay()"), "{src}");
        assert!(src.contains("Locator pay2()"), "{src}");
    }
}
